---
title: "scrape paper"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
#devtools::install_git("https://git.rud.is/hrbrmstr/waffle.git")
```

Library necessary packages
```{r}
library(dplyr)
library(ggplot2)
library(janitor)
#library(waffle)
#library(magrittr)
#library(hrbrthemes)
library(kableExtra)
```


View a categorical variable with `geom_bar`
```{r, echo=FALSE, out.width=c('50%', '50%'), fig.show='hold'}
clean %>% 
  filter(vigorous_activity==c("yes","no")) %>% 
  ggplot(aes(x=vigorous_activity, y= ..prop.., group=1))+
  geom_bar(fill="steelblue", width=0.5)+
  geom_text(stat="count", aes(label=round(..prop.., 3), y=..prop..+ 0.03))+
  scale_y_continuous(labels = scales::percent_format())
```





adding in actual percentages in bar plot
```{r, echo=FALSE}
clean %>% 
  filter(vigorous_activity==c("yes","no")) %>% 
  ggplot(aes(x=vigorous_activity, y= ..prop.., group=1))+
  geom_bar(fill="steelblue", width=0.6)+
  geom_text(stat="count", aes(label=round(..prop.., 3), y=..prop..+ 0.02))+
  scale_y_continuous(labels = scales::percent_format())
```


The elusive waffle 

```{r}
data.frame(
  parts = factor(rep(month.abb[1:3], 3), levels=month.abb[1:3]),
  vals = c(10, 20, 30, 6, 14, 40, 30, 20, 10),
  col = rep(c("blue", "black", "red"), 3),
  fct = c(rep("Thing 1", 3),
          rep("Thing 2", 3),
          rep("Thing 3", 3))
) -> xdf

xdf %>%
  count(parts, wt = vals) %>%
  ggplot(aes(fill = parts, values = n)) +
  geom_waffle(n_rows = 20, size = 0.33, colour = "white", flip = TRUE) +
  scale_fill_manual(
    name = NULL,
    values = c("#a40000", "#c68958", "#ae6056"),
    labels = c("Fruit", "Sammich", "Pizza")
  ) +
  coord_equal() +
  theme_ipsum_rc(grid="") +
  theme_enhance_waffle()
```


```{r}
xdf

```


```{r}
t = as.data.frame(table(clean$vigorous_activity))
t

```



```{r}
waffle(clean$vigorous_activity)

```

