---
title: 'HW 1: Team Formation & Self Regulated Learning'
author: "Course Number - STUDENT NAME"
date: "Date"
output: pdf_document
---

# Part I: Resources for learning R

1. Resource 1: 
    * Found at: 
    * Last updated:
    * How to used:

2. Resource 2: 
    * Found at: 
    * Last updated:
    * How to used:

3. Resource 3: 
    * Found at: 
    * Last updated:
    * How to used:
  
Type `2+2` in the code chunk below. 
```{r}

```
  
# Part II: Becoming a better learner. 

### Procrastination



### Being good at learning is hard!
Answer at least _4_ of the following questions from the reading. 

**What was the most important insight you gained from the reading? **


**What surprised you most in the reading?**


**What did you already know?**


**Have you been taught how to learn before?  Where?  What did you learn about learning?**


**What will you do differently during a lecture, if anything, given what you read?**


**How will you prepare differently for exams, given what you read?**


**Can you think of other good learning practices that the reading didn't mention?**
