---
title: "HW 01- Introduction to the class."
output:
  html_document:
    theme: sandstone
    highlight: tango
    toc: yes
    toc_float: yes
    css: ../css/sandstone.css
  pdf_document: default
---

# Assignment Overview
The purpose of this assignment is to get you working in R Studio, to do a little self reflection and examination of your learning habits, and to recognize the amount of resources to learn R you have available to you. 
 

# Instructions
The specific details for each step are described below. 

* You will answer the questions directly in the Rmarkdown template file provided. 
    - This file is called `hw01_introduction` and is downloaded from the course website. 
    - This must be put in your `homework` folder. Do not click on the file and open it from your browser window. 
* When you are done, spellcheck your work using the spellcheck button in R Studio (2 icons to the left of Knit). 
* Knit the final document. It will automatically open in a new window. 
    - You can knit to html while working on the assignment, but the final document must be a PDF. 
* Rename this file `hw01_username` i.e. `hw01_rdonatello.pdf` 
* Upload this file to Google Drive in the **01 Introduction** folder for your section. 


# Part I: Getting Started with research tools

## Slack
1. Go to http://math315-f19.slack.com and make an account to join our workspace. 
2. Download either the desktop app or the phone app. 
3. Post an introduction to yourself in the #introductions channel. Tell us a little about you! Year, major, hometown, any extracurricular activities, one thing you are hoping to get out of this class, and one concern you have about this class. Oh.. and of course any mention of pets should include a photo!
        
## R and R Studio
You have two choices for using R this semester. You can install the necessary programs on your personal computer, or you can use R studio cloud. If you have already taken or are concurrently enrolled in Math 130 you should install these programs on your own computer. 

1. Install R and R Studio
    * Follow the instructions from Math 130 to install and get started with R and R Studio. https://norcalbiostat.github.io/MATH130/notes/02_setup.html
    * Complete all steps (including installing packages and reading on how to get help)
    * You must install `LaTeX` via the `tinytex` package to turn your homework into PDF. 


2. Everyone learns differently, and the resources that are required in this class (PDS videos, course notes) may not quite work to explain a particular topic. **Find 3 different types of resources to learn R and Statistics. At least 2 must be chosen from provided resources from one of my websites**. These could include a video series other than the ones assigned with the course (passion drive stats), cheatsheets, discussion boards, books, course notes from a different class, etc. For each source: 
    * Explain where you found it (include URL as applicable)
    * When was it last updated (how real time is your source)
    * Describe how you will use this source

3. Using the code chunk provided, calculate `2+2`


# Part II: Becoming a better learner. 
Because we all have room for improvement, here are a few tasks for you to become a better learner. 

First I want you to create a "Learning Journal". This could be a composition notebook, a smaller 5x7 
journal, loose papers in a binder or an electronic document on your computer/cloud. We will be engaging
in several activities throughout the semseter aimed to help you become active and effective learners. 
I will do several check-ins on your journal throughout the semester to ensure that it is being used. 

Some of these tasks will ask you to reflect on a reading. Here is a link to help you understand more
about what that actually means and how to write a reflection. 
https://www.quora.com/What-does-it-mean-to-reflect-on-reading

### Metacognition 

From the materials page on the course website, download and read "MAI and academic achievement in college students". Once you are done, download and take the "Metacognition Awareness Inventory" (also available on the materials page). Submit your scores to Google Drive at this link: https://goo.gl/forms/FYgjJk72T3147e7f1 

Write a reflection on this reading. Were you surprised by the results? 


### Procrastination
Watch this video on creating a cycle of success and tell me **one** concrete plans of action that you already implement, or are willing to give an honest try to do this semester to stay on track and not fall behind.  https://media.csuchico.edu/media/Avoiding+Procrastination/0_wquy9x90


Write this plan in your learning journal. 


### Being good at learning is hard!
From the reading materials page on the course website, download and read the "Learning (Your First Job)" article. Answer at least _4_ of the following questions in this document. Choose one of these to put into your learning journal. 

**What was the most important insight you gained from the reading? **


**What surprised you most in the reading?**


**What did you already know?**


**Have you been taught how to learn before?  Where?  What did you learn about learning?**


**What will you do differently during a lecture, if anything, given what you read?**


**How will you prepare differently for exams, given what you read?**


**Can you think of other good learning practices that the reading didn't mention?**


